//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursos()
        {
            this.Alumnos = new HashSet<Alumnos>();
            this.Cursos_Alumnos = new HashSet<Cursos_Alumnos>();
        }
    
        public int IdCurso { get; set; }
        public Nullable<int> IdMateria { get; set; }
        public Nullable<int> IdProfesor { get; set; }
        public Nullable<int> Cuatrimestre { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos> Alumnos { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos_Alumnos> Cursos_Alumnos { get; set; }
    }
}
