//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampusVirtualEntities : DbContext
    {
        public CampusVirtualEntities()
            : base("name=CampusVirtualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Cursos_Alumnos> Cursos_Alumnos { get; set; }
        public virtual DbSet<Errores_Log> Errores_Log { get; set; }
        public virtual DbSet<Estados_Tipos> Estados_Tipos { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Notas_Alumnos> Notas_Alumnos { get; set; }
        public virtual DbSet<Notas_Tipos> Notas_Tipos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<SubMenu> SubMenu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Usuarios_Tipos> Usuarios_Tipos { get; set; }
        public virtual DbSet<Vw_UsuariosMenu> Vw_UsuariosMenu { get; set; }
        public virtual DbSet<Vw_UsuariosPermisos> Vw_UsuariosPermisos { get; set; }
        public virtual DbSet<Vw_UsuariosPermisosTipos> Vw_UsuariosPermisosTipos { get; set; }
    }
}
