//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas_Alumnos
    {
        public int IdNotaAlumno { get; set; }
        public Nullable<int> IdCursoAlumno { get; set; }
        public Nullable<int> IdNotaTipo { get; set; }
        public Nullable<double> Nota { get; set; }
        public string Observacion { get; set; }
    
        public virtual Cursos_Alumnos Cursos_Alumnos { get; set; }
        public virtual Notas_Tipos Notas_Tipos { get; set; }
    }
}
