//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UsuariosPermisosTipos
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Permiso { get; set; }
        public string TipoUsuario { get; set; }
    }
}
